name: CD - Build and Push to GCP Registry

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GCP credentials
        run: |
          gcloud --quiet auth configure-docker ${{ secrets.GCP_REGISTRY }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.GCP_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest .

      - name: Push image to registry
        run: |
          docker push ${{ secrets.GCP_REGISTRY }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.IMAGE_NAME }}:latest
