name: CD - Build and Push to GCP Registry

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker to use GCP credentials
        run: |
          gcloud --quiet auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build --target service -t us-central1-docker.pkg.dev/decisive-cinema-296013/main/bff-api:latest .

      - name: Push image to registry
        run: |
          docker push us-central1-docker.pkg.dev/decisive-cinema-296013/main/bff-api:latest
